name: speech_to_text
description: A Flutter plugin that exposes device specific speech to text recognition capability. 
version: 5.4.4
homepage: https://github.com/csdcorp/speech_to_text

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
#  speech_to_text_platform_interface: ^2.0.1
  speech_to_text_platform_interface:
    path: ../speech_to_text_platform_interface
  json_annotation: ^4.0.0
  clock: ^1.0.1
  pedantic: ^1.9.2
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.1.7
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^4.0.2
  fake_async: ^1.0.1
  mockito: ^5.0.0
  plugin_platform_interface: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.csdcorp.speech_to_text
        pluginClass: SpeechToTextPlugin
      ios:
        pluginClass: SpeechToTextPlugin
      web:
        pluginClass: SpeechToTextPlugin
        fileName: speech_to_text_web.dart

  assets:
    - assets/sounds/speech_to_text_listening.m4r
    - assets/sounds/speech_to_text_cancel.m4r
    - assets/sounds/speech_to_text_stop.m4r
